/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7Z68qsMF4Hp
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export default function Contact() {
   return (
      <div className='mx-auto py-12'>
         <div className='container px-4 flex flex-col gap-4 md:gap-8'>
            <div className='space-y-2'>
               <h1 className='text-3xl font-bold'>Contact Us</h1>
               <p>
                  If you have any questions or concerns, feel free to contact us using the form below. We typically
                  respond within 24 hours.
               </p>
            </div>
            <div className='grid grid-cols-1 gap-8'>
               <div className='space-y-4'>
                  <div className='grid grid-cols-2 gap-4'>
                     <div className='space-y-2'>
                        <Label htmlFor='name'>Name</Label>
                        <Input id='name' placeholder='Enter your name' />
                     </div>
                     <div className='space-y-2'>
                        <Label htmlFor='email'>Email</Label>
                        <Input id='email' placeholder='Enter your email' type='email' />
                     </div>
                  </div>
                  <div className='space-y-2'>
                     <Label htmlFor='subject'>Subject</Label>
                     <Input id='subject' placeholder='Enter the subject' />
                  </div>
                  <div className='space-y-2'>
                     <Label htmlFor='message'>Message</Label>
                     <Textarea className='min-h-[200px]' id='message' placeholder='Enter your message' />
                  </div>
                  <Button variant="default" className="text-white" >Submit</Button>
               </div>
               <div className='space-y-2'>
                  <h2 className='text-2xl font-bold'>Contact Information</h2>
                  <div className='space-y-2'>
                     <p className='text-gray-500 dark:text-gray-400'>
                        Have questions? We're here to help. Email us at
                        <a href='#'>info@example.com</a>
                        or call us at 1-800-123-4567.
                     </p>
                     <p className='text-gray-500 dark:text-gray-400'>
                        Our office hours are Monday to Friday, 9:00 AM to 5:00 PM.
                     </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   );
}
